name: Put to AWS S3 bucket via access point by schedule
on:
  schedule:
    - cron:  '0 0/6 * * *'
jobs:
  deploy:
    name: Put to AWS S3 Access Point
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - name: Run AWS CLI command to put with object tag and correct content type
      env:
        aws-s3-tag: ${{ secrets.AWS_S3_TAG }}
        aws-s3-bucket: ${{ secrets.AWS_S3_BUCKET }}
      run: aws s3api put-object --bucket ${{ secrets.AWS_S3_BUCKET }} --content-type text/html --key index.html --body ./index.html --tagging "${{ secrets.AWS_S3_TAG }}"
